### ISSUE TITLE
jackhmmer -E 10 returns far less alignment than -E 1e-3 for some query.

### ISSUE THREAD

**Issue by kad-ecoli** [EddyRivasLab/hmmer#134]
When using jackhmmer (3.1b2) on 64bit CentOS Linux 6.7, I found that for some query, -E 10 returns less hits than -E 1e-3. Here is my query sequence:

\>T0606
SAQLEGSYIFCGNPLLDKLSDEDIREQLKAFVTGKTDSIRTDTELSFDIYVSETDYALIRYADSLCERLN
DAGADVQIKQYSGTGLRSRAVSGKYEAFLSESDLVSTDALENADYIILDSAEG

I search it against uniref90 version 2017_07, using the following two commands:

$ jackhmmer --cpu 1 -N 3 -E 10 --incE 1e-3 -A seq.upstream.first --tblout seq.upstream.tbl seq.fasta /scratch/aminoproject_fluxoe/zcx/uniref90/uniref90.fasta
$ jackhmmer --cpu 1 -N 3 -E 1e-3 --incE 1e-3 -A seq.1e-3.upstream.first --tblout seq.1e-3.upstream.tbl seq.fasta /scratch/aminoproject_fluxoe/zcx/uniref90/uniref90.fasta

You can find the output file in the attachments.
Here, seq.upstream.first and seq.upstream.tbl are the alignment and tabular output using report e-value threshold -E 10, respectively.
seq.1e-3.upstream.first and seq.1e-3.upstream.tbl are the alignment and tabular output using report e-value threshold -E 1e-3, respectively.
For the query T0606, -E 10 only lead to 523 sequence in --tblout, 19 alignments in -A, while -E 1e-3 lead to lead to 67872 sequences in --tblout, 66715 alignments in -A.
However, according to definition of -E (report sequences <= this E-value threshold in output), the higher -E is, the more hit it should report, not the other way around. Is there some misunderstanding here?

[E10.zip](https://github.com/EddyRivasLab/hmmer/files/1632524/E10.zip)
[E1e-3.zip](https://github.com/EddyRivasLab/hmmer/files/1632525/E1e-3.zip)

**Comment by cryptogenomicon** [comment]
This is "correct" behavior; an edge case of how E-value statistics are calculated for domains.

HMMER calculates a "conditional E-value" for each individual domain, which is the number of domains you'd expect to find by chance (at a given score) in the list of top-scoring hits. That is: if you accepted that each of the top scoring _sequences_ is a homolog, now you're trying to calculate the statistical significance of individual _domains_. Arguably, the search space for additional domains is smaller -- just the top hits. The number of top-scoring hits is called `<domZ>`. It is much smaller than Z, the size of the database overall (in number of sequences). `<domZ>` is the number of sequences that pass the E-value _reporting_ threshold, set by the `-E` option.

What's happening in your example is that with `-E10`, you get a larger `<domZ>` than with `-E1e-3`, and therefore the per-domain conditional E-values are more stringent. 

After round 1 of a search with your query against UniRef90:
 -E10 :  domZ=48,  8 seqs included in new ali
 -E1e-3: domZ=9,  12 seqs included in new ali

The difference is four domains, and all four are in `UniRef90_UPI000A2AA2F6`. Looking at domain 2, for example:

`-E10` search:
```
 #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
  2 ?   10.0   0.0    0.0021   2.9e+03      68     106 ..     107     145 ..      96     161 .. 0.84
```

`-E1e-3` search:
```
 #    score  bias  c-Evalue  i-Evalue hmmfrom  hmm to    alifrom  ali to    envfrom  env to     acc
---   ------ ----- --------- --------- ------- -------    ------- -------    ------- -------    ----
  2 !   10.0   0.0    0.0004   2.9e+03      68     106 ..     107     145 ..      96     161 .. 0.84
                      ^^^^^^
```

In the `-E1e-3` search, the domain gets an E-value 5x lower, because domZ is 5x smaller.

After that, subsequent iterations are searching with different models, and differences will accumulate.
