### ISSUE TITLE
A new case causing error: "backconverted subseq didn't end at expected length"

### ISSUE THREAD

**Issue by bioinformatist** [EddyRivasLab/hmmer#153]
Hi, when I use `hmmsearch` with its `-A` parameter on for MSAs, it raise an error as:

```pre
//
Fatal exception (source file p7_alidisplay.c, line 771):
backconverted subseq didn't end at expected length (Bacteria_CPR_WWE3_RIFCSPHIGHO2_01_FULL_WWE3_35_17/Ribosomal_L14)
Aborted (core dumped)
```

The version of my HMM binaries is HMMER 3.2.1 (June 2018, latest).
To reproduce this problem, I would provide example files here:

[all.hmm.gz](https://github.com/EddyRivasLab/hmmer/files/3102913/all.hmm.gz)

[one_bac.fasta.gz](https://github.com/EddyRivasLab/hmmer/files/3102915/one_bac.fasta.gz)

And the command I used is:

```bash
hmmsearch -A test --cpu 2 all.hmm one_bac.fasta
```

which can finish normally if the `-A` is removed.

Can you help with this bug?

Thanks in advance.

Associated issue:

https://github.com/EddyRivasLab/hmmer/issues/135#issue-301079668

**Comment by cryptogenomicon** [comment]
Your file `one_bac.fasta` is not a valid FASTA file. It contains gap characters, `-`. Because it's got a `.fasta` suffix, the input parser is trying to parse it as an unaligned FASTA file, and hmmsearch is getting confused by the gaps.

To work around the problem, you can specify that the input file format is really aligned fasta (afa) format:

    hmmsearch -A test --tformat afa all.hmm one_bac.fasta

Still, you should get a more informative error message for this problem. I've just checked in a fix that will report the bad format before trying to use the misparsed sequence. The fix will appear in the next HMMER3 release.
