### ISSUE TITLE
3.3.1 version: Target sequence length > 100K, over comparison pipeline limit.

### ISSUE THREAD

**Issue by guilhemfaure** [EddyRivasLab/hmmer#205]
Hello,

I obtained the following error in the new version of hmmer (3.3.1) when running a hmmsearch on protein sequences:
Target sequence length > 100K, over comparison pipeline limit.

This worked with hmmer 3.3 but not with the new version (3.3.1).
Is there a way to remove this limit?

The reason, I have so big proteins is because I'm mimicking a translated hmmsearch, I translated nt sequences into 6 frames and generates 6 huge artificial proteins, one for each frame with * as stop codon -- this works quite well. 
So, it the target sequence length cannot be increased, I was wondering if there is a better solution to do translated hmmsearch?

Thanks for your help!
Best,
Guilhem

**Comment by cryptogenomicon** [comment]
HMMER generally assumes in its probability models that target sequences are single proteins. (Except for `nhmmer`/`nhmmscan`, which are for DNA/DNA comparisons.) It's probably not a good idea to translate into six frames into six long "polypeptides" like you're doing, because HMMER will analyze them as if they're just six proteins. HMMER also doesn't particularly like * characters, which aren't legal IUPAC input characters in protein sequences. 

The best way to do your six-frame translation for HMMER is such that each ORF is a separate sequence, with no *'s.
