### ISSUE TITLE
Error: Unable to guess alphabet for the FASTA-formattedquery file

### ISSUE THREAD

**Issue by gy-chop** [EddyRivasLab/hmmer#210]
Hello,
I met an error "Error: Unable to guess alphabet for the FASTA-formattedquery file" when I tried using a 35nt query (AGAAAGAGAAAGAGAAAAGGAACAGCAGGAAGAGA) for any nhmmer search (hmmer v3.3.1). Could you please advise why this happened? Is it because there are only three types of bases but no 'T' in the query?

Thanks for your time,

**Comment by traviswheeler** [comment]
Yes, the failure to guess the alphabet is caused by the lack of a 'T'.  You can overcome this by specifying the alphabet using the --dna flag, like: 
`% nhmmer --dna --qformat fasta query.fa target.fa`

Note: this highlights a formatting error in this warning message (a missing space in "formattedquery".  I'll send a PR w/ a fix tomorrow.

**Comment by gy-chop** [comment]
Thanks. That's very helpful.
