### ISSUE TITLE
Issue with small domains in HMMER3 fixed?

### ISSUE THREAD

**Issue by michael-imbeault** [EddyRivasLab/hmmer#231]
Been using HMMER in the past few years for the detection of small domains (zinc fingers) - and as you know, HMMER3 has a specific problem with this while HMMER2 doesn't (described in 2009 at http://cryptogenomicon.org/missing-fingers.html).

Was this ever fixed in HMMER3, or is my best bet to continue using HMMER2? The hack of using many alignment / models and the union of the results in HMMER3 is not something I want to do.

**Comment by cryptogenomicon** [comment]
Unfortunately this won't be fixed in HMMER3, because it seems to be pretty fundamental to using local alignment (H3) instead of glocal alignment (H2). 

HMMER4 uses a new model design that allows both local and glocal alignment, so it should do much better, but I still don't know when HMMER4 will be ready for testing.

**Comment by michael-imbeault** [comment]
Alright no worries, for now HMMER2 is doing a good job for our needs.
