### ISSUE TITLE
hmmsearch/scan does not recognize *.hmm database

### ISSUE THREAD

**Issue by B10inform** [EddyRivasLab/hmmer#249]
HI,

I am getting issues with the asterisk on the database path while using hmmscan.

**hmmscan/hmmsearch works:**
 hmmsearch --domtblout SAMPLE ./motifs/*/PF002.hmm XP_526.fasta > log

**hmmscan/hmmsearch does not work:**
 hmmsearch --domtblout SAMPLE ./motifs/* /*.hmm XP_526.fasta > log

**Error message:**
Incorrect number of command line arguments.
Usage: hmmsearch [options] <hmmfile> <seqdb>

where most common options are:
  -h : show brief help on version and usage

To see more help on available options, do hmmsearch -h

Any help Please??

Thanks

**Comment by cryptogenomicon** [comment]
You're not providing a single file as an argument (which is what these programs take, as the documentation says), which is why your command with `*` expansions isn't working. If you want to use a command line glob `*` expansion to search many individual HMM files in a single command line, use something like `xargs`. If you want to treat many HMM files as a "database" (as in Pfam files), concatenate individual HMM files together with `cat`.
