### ISSUE TITLE
hmmalign cannot open my sequence file even though it is located in my hmmer directory

### ISSUE THREAD

**Issue by orspanish** [EddyRivasLab/hmmer#299]
I am currently trying to align a test set of protein sequences to an HMM that I built with hmmbuild. My MSA file is a Stockholm file and I have repeatedly tried different ways to move this file into the hmmer directory on my device. This file shows up in the finder directory for hmmer but not in the terminal directory. I'm pretty sure this is preventing me from being able to run the hmmalign command since I keep getting an error saying that my MSA file cannot be opened. How can I fix this issue? Thanks!

**Comment by cryptogenomicon** [comment]
This sounds like an issue with using the command line and manipulating files in general, rather than something specific to HMMER. See if you have someone you can ask about using the command line; or experiment with being able to use other simple command line tools to see your file, such as `more` or `cat`.
