### ISSUE TITLE
Is there any flag in jackhmmer to limit the sequence number?

### ISSUE THREAD

**Issue by everburstSun** [EddyRivasLab/hmmer#330]
Sometimes the output of jackhmmer would contain millions of sequences. But I wanted to set a certein limit to the number like 10000. Have this implemented officially by you guys? 

I noticed in the paper of [Alphafold 3](https://static-content.springer.com/esm/art%3A10.1038%2Fs41586-024-07487-w/MediaObjects/41586_2024_7487_MOESM1_ESM.pdf) (page 2) that they added a flag called _seq_limit_, while I couldn't find it in the HMMER user guide.

**Comment by cryptogenomicon** [comment]
No, sorry, we don't have any flag for that. It's probably undesirable to take the first N hits that are found because most databases are in an idiosyncratic order; you'd get a biased sample. It's also undesirable to take the top N hits, because that's a highly biased sample.

What I recommend instead is to save the tabular output (`--tblout` and/or `--domtblout`), downsample the lines of the tabular output any way you want, fetch those sequences or subsequences from the db, and use `hmmalign` to produce the alignment of the downsampled set.

**Comment by everburstSun** [comment]
Thank you very much for the quick response!
